<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue'
import { BookOpen, FileArchive, FileSearch, RefreshCw, Search, Trash2, Upload, X } from 'lucide-vue-next'
import { api, ApiError } from '@/api/client'
import ConfirmDialog from '@/components/ConfirmDialog.vue'
import EmptyState from '@/components/EmptyState.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import ToastMessage from '@/components/ToastMessage.vue'
import type { KnowledgeItem, Page, SearchResult } from '@/types'

const items = ref<Page<KnowledgeItem>>({ items: [], total: 0, page: 1, page_size: 20, pages: 0 }); const loading = ref(true); const error = ref(''); const toast = ref(''); const status = ref(''); const uploadOpen = ref(false); const search = ref(''); const results = ref<SearchResult[]>([]); const searchLoading = ref(false); const file = ref<File | null>(null); const title = ref(''); const uploadLoading = ref(false); const deleting = ref<KnowledgeItem | null>(null); let poll: number | undefined
function date(value: string) { return new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) }
async function load() { loading.value = true; error.value = ''; try { items.value = await api.listKnowledge({ page: 1, page_size: 20, status: status.value }) } catch (e) { error.value = e instanceof ApiError ? e.message : '知识库加载失败' } finally { loading.value = false } }
async function doSearch() { if (!search.value.trim()) return; searchLoading.value = true; error.value = ''; try { const result = await api.searchKnowledge(search.value); results.value = result.items } catch (e) { error.value = e instanceof ApiError ? e.message : '检索失败' } finally { searchLoading.value = false } }
function chooseFile(event: Event) { const selected = (event.target as HTMLInputElement).files?.[0]; if (selected) file.value = selected }
async function upload() { if (!file.value) return; uploadLoading.value = true; try { await api.uploadKnowledge(file.value, title.value); uploadOpen.value = false; file.value = null; title.value = ''; toast.value = '文件已上传，正在处理和建立索引'; await load(); startPolling() } catch (e) { error.value = e instanceof ApiError ? e.message : '上传失败，请检查文件类型和大小' } finally { uploadLoading.value = false } }
async function remove() { if (!deleting.value) return; try { await api.deleteKnowledge(deleting.value.id); toast.value = '知识文档已删除'; deleting.value = null; await load() } catch (e) { error.value = e instanceof ApiError ? e.message : '删除失败' } }
function startPolling() { stopPolling(); poll = window.setInterval(async () => { if (items.value.items.some((item) => item.status === 'processing')) await load(); else stopPolling() }, 3000) }
function stopPolling() { if (poll) { window.clearInterval(poll); poll = undefined } }
onMounted(async () => { await load(); if (items.value.items.some((item) => item.status === 'processing')) startPolling() }); onBeforeUnmount(stopPolling)
</script>
<template>
  <div class="page-wrap"><ToastMessage :message="toast" /><header class="page-header"><div><div class="section-kicker">KNOWLEDGE DESK / INDEX</div><h1>知识库</h1><p class="page-subtitle">管理已脱敏的支持文档，并检索可引用的原始片段。</p></div><button class="button primary" @click="uploadOpen = true"><Upload :size="17" /> 上传文档</button></header>
    <section class="knowledge-grid"><section class="panel search-panel"><div class="section-kicker">RETRIEVAL / TOP-K 5</div><h2>检索知识库</h2><div class="knowledge-search"><Search :size="17" /><input v-model="search" placeholder="输入问题，例如：如何重置密码" @keyup.enter="doSearch" /><button class="button primary" :disabled="searchLoading || !search.trim()" @click="doSearch">{{ searchLoading ? '检索中…' : '检索' }}</button></div><div v-if="searchLoading" class="search-loading"><span class="loader" /> 正在查找相关片段</div><div v-else-if="search.length && !results.length" class="search-empty"><FileSearch :size="22" /><p>还没有检索结果</p><span>尝试换一种描述，或等待文档完成索引。</span></div><div v-else-if="results.length" class="result-list"><article v-for="result in results" :key="result.chunk_id" class="result-item"><div class="result-meta"><strong>{{ result.title }}</strong><span>CHUNK {{ result.chunk_index }} · {{ Math.round(result.similarity_score * 100) }}% 相似</span></div><p>{{ result.content }}</p></article></div><div v-else class="search-placeholder"><BookOpen :size="26" /><p>从已就绪的文档中查找答案依据</p><span>检索结果会显示来源标题、片段和相似度。</span></div></section><section class="panel knowledge-summary"><div class="section-kicker">INDEX STATUS</div><h2>{{ items.total }} <small>documents</small></h2><div class="status-breakdown"><div><StatusBadge value="ready" /><strong>{{ items.items.filter(i => i.status === 'ready').length }}</strong></div><div><StatusBadge value="processing" /><strong>{{ items.items.filter(i => i.status === 'processing').length }}</strong></div><div><StatusBadge value="failed" /><strong>{{ items.items.filter(i => i.status === 'failed').length }}</strong></div></div></section></section>
    <section class="knowledge-list-section"><div class="list-toolbar"><div><div class="section-kicker">DOCUMENT REGISTER</div><h2>文档列表</h2></div><div class="toolbar-actions"><select v-model="status" aria-label="筛选文档状态" @change="load"><option value="">全部状态</option><option value="processing">处理中</option><option value="ready">可用</option><option value="failed">失败</option></select><button class="icon-button" title="刷新文档" aria-label="刷新文档" @click="load"><RefreshCw :size="16" /></button></div></div><div v-if="loading" class="table-shell"><div class="skeleton-row" v-for="i in 3" :key="i"><span /><span /><span /><span /></div></div><div v-else-if="error" class="notice error-notice"><span>{{ error }}</span><button class="button secondary" @click="load">重试</button></div><div v-else-if="!items.items.length" class="panel"><EmptyState title="知识库还没有文档" message="上传已脱敏的 TXT 或 PDF 文档后，后台会自动切片和建立索引。" /></div><div v-else class="table-shell"><div class="knowledge-row heading"><span>文档</span><span>状态</span><span>切片</span><span>上传时间</span><span></span></div><div v-for="item in items.items" :key="item.id" class="knowledge-row"><div class="file-cell"><span class="file-icon"><FileArchive :size="17" /></span><div><strong>{{ item.title }}</strong><small>{{ item.file_name }} · {{ Math.ceil(item.file_size_bytes / 1024) }} KB</small></div></div><div><StatusBadge :value="item.status" /><small v-if="item.error_message" class="file-error">{{ item.error_message }}</small></div><span>{{ item.chunk_count ?? '—' }}</span><time>{{ date(item.created_at) }}</time><button class="icon-button danger-icon" title="删除文档" aria-label="删除文档" @click="deleting = item"><Trash2 :size="16" /></button></div></div></section>
    <Teleport to="body"><div v-if="uploadOpen" class="dialog-backdrop" @click.self="uploadOpen = false"><section class="dialog form-dialog"><button class="dialog-close icon-button" aria-label="关闭" @click="uploadOpen = false"><X :size="18" /></button><div class="dialog-kicker">DOCUMENT REGISTER / ADMIN</div><h2>上传知识文档</h2><p class="muted">仅上传已脱敏的 TXT 或 PDF 文件，不要上传个人资料或密钥。</p><form @submit.prevent="upload"><label>文档标题<input v-model="title" required placeholder="例如：账户安全手册" /></label><label class="file-drop"><Upload :size="20" /><span>{{ file?.name || '选择 TXT 或 PDF 文件' }}</span><input type="file" accept=".txt,.pdf,text/plain,application/pdf" required @change="chooseFile" /></label><div class="dialog-actions"><button type="button" class="button secondary" @click="uploadOpen = false">取消</button><button class="button primary" :disabled="uploadLoading">{{ uploadLoading ? '上传中…' : '开始上传' }}</button></div></form></section></div></Teleport><ConfirmDialog :open="Boolean(deleting)" title="删除这份知识文档？" message="删除后关联的切片和向量索引也会被移除，且无法恢复。" @cancel="deleting = null" @confirm="remove" />
  </div>
</template>
