<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { ChevronLeft, ChevronRight, Filter, Plus, RefreshCw, Search, X } from 'lucide-vue-next'
import { api, ApiError } from '@/api/client'
import EmptyState from '@/components/EmptyState.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import ToastMessage from '@/components/ToastMessage.vue'
import { auth } from '@/stores/auth'
import type { Page, Ticket } from '@/types'

const router = useRouter(); const isStaff = computed(() => auth.user.value?.role !== 'customer')
const page = ref<Page<Ticket>>({ items: [], total: 0, page: 1, page_size: 20, pages: 0 }); const loading = ref(true); const error = ref(''); const toast = ref(''); const status = ref(''); const priority = ref(''); const classification = ref(''); const query = ref(''); const showCreate = ref(false); const submitting = ref(false)
const form = ref({ title: '', description: '', classification: '' })
const filtered = computed(() => query.value ? page.value.items.filter((ticket) => `${ticket.title} ${ticket.customer_name} ${ticket.classification}`.toLowerCase().includes(query.value.toLowerCase())) : page.value.items)
async function load(nextPage = page.value.page) { loading.value = true; error.value = ''; try { page.value = await api.listTickets({ page: nextPage, page_size: 20, status: status.value, priority: priority.value, classification: classification.value }) } catch (e) { error.value = e instanceof ApiError ? e.message : '工单加载失败' } finally { loading.value = false } }
async function create() { submitting.value = true; error.value = ''; try { await api.createTicket(form.value); showCreate.value = false; form.value = { title: '', description: '', classification: '' }; toast.value = '工单已创建，正在进入分析队列'; await load(1) } catch (e) { error.value = e instanceof ApiError ? e.message : '创建失败，请稍后重试' } finally { submitting.value = false } }
function date(value: string) { return new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) }
onMounted(() => load())
</script>
<template>
  <div class="page-wrap"><ToastMessage :message="toast" @click="toast = ''" /><header class="page-header"><div><div class="section-kicker">{{ isStaff ? 'SHIFT DESK / INBOX' : 'CUSTOMER DESK / TICKETS' }}</div><h1>{{ isStaff ? '工单工作台' : '我的工单' }}</h1><p class="page-subtitle">{{ isStaff ? '按状态和优先级处理当前队列，保持每一步都有记录。' : '查看你提交的工单与已发送回复。' }}</p></div><button v-if="!isStaff" class="button primary" @click="showCreate = true"><Plus :size="17" /> 创建工单</button></header>
    <section class="metric-strip"><div><span class="metric-label">当前结果</span><strong>{{ page.total }}</strong><small>条工单</small></div><div><span class="metric-label">待处理</span><strong>{{ page.items.filter(t => t.status === 'open').length }}</strong><small>本页</small></div><div><span class="metric-label">审核中</span><strong>{{ page.items.filter(t => t.status === 'in_review').length }}</strong><small>本页</small></div><div class="metric-note">STATUS FIRST / API-SOURCED DATA</div></section>
    <section class="filter-bar"><div class="search-field"><Search :size="16" /><input v-model="query" placeholder="搜索标题、客户或分类" /></div><select v-model="status" aria-label="筛选状态" @change="load(1)"><option value="">全部状态</option><option value="open">待处理</option><option value="in_review">审核中</option><option value="replied">已回复</option><option value="closed">已关闭</option></select><select v-model="priority" aria-label="筛选优先级" @change="load(1)"><option value="">全部优先级</option><option value="urgent">紧急</option><option value="high">高</option><option value="normal">普通</option><option value="low">低</option></select><button class="button ghost" aria-label="刷新工单" title="刷新工单" @click="load(page.page)"><RefreshCw :size="16" /> 刷新</button></section>
    <div v-if="loading" class="table-shell"><div class="skeleton-row" v-for="i in 5" :key="i"><span /><span /><span /><span /></div></div><div v-else-if="error" class="notice error-notice"><strong>无法读取工单</strong><span>{{ error }}</span><button class="button secondary" @click="load(page.page)">重试</button></div><div v-else-if="!filtered.length" class="panel"><EmptyState title="这里还没有工单" message="调整筛选条件，或创建一条新的工单开始处理。" /></div><section v-else class="table-shell"><div class="table-heading"><span>工单 / 客户</span><span>状态</span><span>优先级</span><span>分类</span><span>更新</span><span></span></div><button v-for="ticket in filtered" :key="ticket.id" class="ticket-row" @click="router.push(`/tickets/${ticket.id}`)"><div class="ticket-primary"><span class="ticket-ref">#{{ ticket.id.slice(0, 8) }}</span><strong>{{ ticket.title }}</strong><small>{{ ticket.customer_name }} · {{ ticket.reply_count }} 条回复</small></div><StatusBadge :value="ticket.status" /><span class="priority" :class="`priority-${ticket.priority}`"><i />{{ ticket.priority }}</span><span class="classification">{{ ticket.classification || '未分类' }}</span><time>{{ date(ticket.updated_at) }}</time><ChevronRight :size="17" class="row-arrow" /></button><footer class="pagination"><span>第 {{ page.page }} / {{ Math.max(page.pages, 1) }} 页，共 {{ page.total }} 条</span><div><button class="icon-button" :disabled="page.page <= 1" aria-label="上一页" @click="load(page.page - 1)"><ChevronLeft :size="17" /></button><button class="icon-button" :disabled="page.page >= page.pages" aria-label="下一页" @click="load(page.page + 1)"><ChevronRight :size="17" /></button></div></footer></section>
    <Teleport to="body"><div v-if="showCreate" class="dialog-backdrop" @click.self="showCreate = false"><section class="dialog form-dialog"><button class="dialog-close icon-button" aria-label="关闭" @click="showCreate = false"><X :size="18" /></button><div class="dialog-kicker">NEW TICKET / CUSTOMER</div><h2>创建工单</h2><form @submit.prevent="create"><label>标题<input v-model="form.title" required maxlength="200" placeholder="简明描述你的问题" /></label><label>问题描述<textarea v-model="form.description" required rows="6" placeholder="提供尽可能完整的背景信息" /></label><label>分类（可选）<input v-model="form.classification" placeholder="例如：account / billing" /></label><div class="dialog-actions"><button type="button" class="button secondary" @click="showCreate = false">取消</button><button class="button primary" :disabled="submitting">{{ submitting ? '提交中…' : '提交工单' }}</button></div></form></section></div></Teleport>
  </div>
</template>
